# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Víctor Bárcena Mena (abito2)
# Description of the Site
description: My personal page
# URL of Image of the Site
site-image: "https://github.com/vbarcena2020/My_personal_page/blob/master/assets/images/site_image.png?raw=true"
# Keywords of the Site
site-keywords: Site
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: "https://github.com/vbarcena2020/My_personal_page/blob/master/assets/images/portada_img.png?raw=true"

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: victorbameba@gmail.com
facebook_username: /
twitter_username: abito_2
instagram_username: abito_2
linkedin_username: victor-barcena-mena-400155266
github_username:  vbarcena2020
youtube_channel_id: UCkxcA536jBns0uDtC1Zzx0A
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: sibprc54pysl7opy4rbxee573

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: abito2

# Name of the Author
author-name: vbarcena2020(abito2)
# URL for the Image of the Author
author-image: "https://github.com/vbarcena2020/My_personal_page/blob/master/assets/images/deku.jpg?raw=true"
# 60 Words About the Author
author-about: I am a student in software robotics engineering, at King Juan Carlos University, Spain.
author-about1: I member of Robotech association and member of Nocom-pila, winner of European RoboCup@Home Education 2022, Portugal.
author-about2: I am going to use this blog to publish my progress in some proyects or subjects like "Robótica móvil".
author-about3: "My skills:"

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/vbarcena2020

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
